import os
import datetime
import uuid
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from config.settings import settings

class GoogleCalendarService:
    """
    Service to handle Google Calendar integration and Meet link generation.
    Requires 'credentials.json' in the root directory for initial setup.
    """
    
    SCOPES = ['https://www.googleapis.com/auth/calendar.events']
    TOKEN_PATH = 'token.json'
    CREDENTIALS_PATH = 'credentials.json'

    @classmethod
    def _get_service(cls):
        creds = None
        # The file token.json stores the user's access and refresh tokens
        if os.path.exists(cls.TOKEN_PATH):
            creds = Credentials.from_authorized_user_file(cls.TOKEN_PATH, cls.SCOPES)
            
        # If there are no (valid) credentials available, let the user log in.
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
            else:
                if not os.path.exists(cls.CREDENTIALS_PATH):
                    return None # Need credentials.json from Google Cloud Console
                
                flow = InstalledAppFlow.from_client_secrets_file(cls.CREDENTIALS_PATH, cls.SCOPES)
                creds = flow.run_local_server(port=0)
                
            # Save the credentials for the next run
            with open(cls.TOKEN_PATH, 'w') as token:
                token.write(creds.to_json())

        return build('calendar', 'v3', credentials=creds)

    @classmethod
    def create_meet_link(cls, event_name, start_time, duration_minutes=60):
        """
        Creates a Google Calendar event and returns the Google Meet link.
        """
        try:
            service = cls._get_service()
            if not service:
                print("Google Calendar Service not initialized. Please provide credentials.json")
                return None

            end_time = start_time + datetime.timedelta(minutes=duration_minutes)
            
            event = {
                'summary': event_name,
                'description': 'Event generated by EventEngine',
                'start': {
                    'dateTime': start_time.isoformat(),
                    'timeZone': 'UTC',
                },
                'end': {
                    'dateTime': end_time.isoformat(),
                    'timeZone': 'UTC',
                },
                'conferenceData': {
                    'createRequest': {
                        'requestId': str(uuid.uuid4()),
                        'conferenceSolutionKey': {'type': 'hangoutsMeet'}
                    }
                },
            }

            created_event = service.events().insert(
                calendarId='primary', 
                body=event, 
                conferenceDataVersion=1
            ).execute()

            link = created_event.get('hangoutLink')
            if not link:
                print(f"DEBUG: Event created but no hangoutLink found. Event data: {created_event}")
            return link
            
        except Exception as e:
            print(f"Error creating Google Meet link: {str(e)}")
            # Log the specific error to a file for easier debugging
            with open("google_api_debug.log", "a") as f:
                f.write(f"[{datetime.datetime.now()}] Error: {str(e)}\n")
            return None
